---
- name: Install 7zip
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - p7zip-full
    - p7zip-rar

- name: Checkout repo
  git: repo=https://github.com/mevacoin/mevacoin.git
    dest=/root/tmp/checkout
    update=yes
    accept_hostkey=yes
    clone=false
    update=false
  register: gitresult

- name: Check that the bootstrap already exists
  stat:
    path: "/root/bootstrap.7z"
  register: stat_result

- name: Download Boostrap
  when: mevacoin_node_boostrap | length > 0 and not stat_result.stat.exists
  get_url:
    url: "{{ mevacoin_node_boostrap }}"
    dest: "/root/bootstrap.7z"

- name: Extract Boostrap
  when: mevacoin_node_boostrap | length > 0 and not stat_result.stat.exists
  shell: "7z x *.7z"

- name: Create Kryptokrona Node Container
  docker_container:
    name: "{{ docker_node_container_name }}"
    image: "{{ docker_kryptokona_image }}:latest"
    command: /bin/echo success
    state: present
    force_kill: yes
    recreate: yes
    volumes:
      - "/root/.mevacoin:/root/.mevacoin"
    networks:
      - name: "host"

- name: Start Kryptokrona Node Container
  docker_container:
    name: "{{ docker_node_container_name }}"
    image: "{{ docker_kryptokona_image }}:latest"
    command: "/usr/src/mevacoin/start.sh"
    volumes:
      - "/root/.mevacoin:/root/.mevacoin"
    networks:
      - name: "host"

- name: Install Restart Node Script
  template:
    src: scripts/restart_node.sh
    dest: /root/restart_node.sh

- name: Change script ownership
  ansible.builtin.file:
    path: /root/restart_node.sh
    mode: "0777"

- name: CRON job to restart node weekly
  cron:
    name: "restart node"
    special_time: "weekly"
    job: "/root/restart_node.sh"
