name: Build Mevacoin Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /opt/android-sdk
      ANDROID_NDK_HOME: /opt/android-sdk/ndk/25.2.9519653
      BOOST_INSTALL_DIR: ${{ github.workspace }}/boost-android
      MEVACOIN_INSTALL_DIR: ${{ github.workspace }}/mevacoin-build

    steps:
      # 1️⃣ Checkout repository Mevacoin
      - name: Checkout Mevacoin
        uses: actions/checkout@v3
        with:
          repository: pasqualelembo78/mevacoin_for_android
          path: mevacoin

      # 2️⃣ Checkout Boost-for-Android
      - name: Checkout Boost-for-Android
        uses: actions/checkout@v3
        with:
          repository: pasqualelembo78/Boost-for-Android
          path: boost-android

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential git unzip python3

      # 4️⃣ Build Boost
      - name: Build Boost for Android
        run: |
          cd boost-android
          chmod +x build-android.sh
          ./build-android.sh \
            $ANDROID_NDK_HOME \
            --arch=arm64-v8a \
            --with-libraries=system,thread,filesystem,date_time,chrono,regex,serialization,program_options \
            --prefix=$BOOST_INSTALL_DIR

      # 5️⃣ Configure Mevacoin with Boost
      - name: Configure Mevacoin
        run: |
          mkdir -p $MEVACOIN_INSTALL_DIR
          cd $MEVACOIN_INSTALL_DIR
          cmake ../mevacoin \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-31 \
            -DCMAKE_BUILD_TYPE=Release \
            -DBOOST_ROOT=$BOOST_INSTALL_DIR \
            -DBoost_NO_SYSTEM_PATHS=ON

      # 6️⃣ Build Mevacoin
      - name: Build Mevacoin
        run: |
          cd $MEVACOIN_INSTALL_DIR
          make -j$(nproc)

      # 7️⃣ Upload artifacts (aggiornato a v4)
      - name: Upload Mevacoin APK/Binaries
        uses: actions/upload-artifact@v4
        with:
          name: mevacoin-android
          path: $MEVACOIN_INSTALL_DIR
